# Generated by Django 5.0.6 on 2024-06-06 07:16

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=20, verbose_name='İstifadəçi soyadı')),
                ('age', models.IntegerField(verbose_name='Yaşı')),
                ('country', models.CharField(max_length=30, verbose_name='Ölkə')),
                ('skills', models.TextField(max_length=100, verbose_name='Bacarıqlar')),
                ('hobbies', models.TextField(max_length=100, verbose_name='Hobilər')),
                ('fobbies', models.TextField(max_length=100, verbose_name='Fobilər')),
                ('languages', models.TextField(max_length=100, verbose_name='Dillər')),
                ('desiredcountry', models.CharField(max_length=30, verbose_name='Getmək istədiyi ölkə')),
                ('favmeal', models.CharField(max_length=20, verbose_name='Sevimli yeməyi')),
                ('favanimal', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sevimli heyvan fotosu')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi adı')),
            ],
        ),
    ]
